[package]
name = "age-credentials"
version = "0.2.0"
edition = "2024"
description = "Age-based identity and credential management library"
license = "MIT"
repository = "https://github.com/mroczect/age-credentials"

[dependencies]
librage = { git = "https://github.com/mroczect/librage.git" }
thiserror = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zeroize = { version = "1", features = ["serde"] }
dirs = "6"
sha2 = "0.11"
eyre = "0.6.12"
color-eyre = "0.6.5"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tempfile = "3.27.0"
age = "0.12.1"
